language: java
sudo: false
deploy:
  provider: releases
  api_key:
    secure: Z/D9i/lx2zfb2L/f4z8/YVWVmOWLPfUCj38bD6PrN3rH3Af8gbZxpLo+UUOqJrACLKzHN2st6X0XfyJtLi9xvBDGLgYEA60qx6CjCinN2n5K2807NbMpVTBjKcrN69iUwCkhMc1U47vw+42I+QfxNqz87/YQy1gZgqlQie2yfoG8kjYV8XQZYTzLj+eWveCsJ73ww4ozUNfkzEy1howwnKBMf1DndpBW3A4Dru+H0SufvsvWaAg9m60pOggtKgxpGUd3NibuOfTTuOVWU3WGHnA44GzBCl8/HGLlY6424rXrPjNQCz43hQ9o0s8gX0XqXEaRiZwndX6y9UEM7jlCWzGf09iVWJ6OIVMHM+QYxn0R3w6lkWVHajjQDvxmTxvm0R+eCtJmitKuT9xgUl8bPCjU5ONqiKAa+D3JDfvNpZgCJmroiD1XEA9PQH0nh5NkjbZGX5vBKg/WOxwUAE6PcVaXXt8U9/L9wKDppoaoHQ08bwVRno32wBo5m1xnM+RjqaydLKg3Fzf+wMmHeTA5faAvy7lmquUMqyPHg4NdldK/WX7IQSzzA7wI3hpjYlwxaPqrNBN+yy/hLsD4wD9vdDh0yoGx9Tq0rZ9JmSUfho2hFVMTkgVh68WAw5eKBnLd7AR4ZJipkdDNrZ3n5YXHGsISS9V+hxFeAvyVMfu1/VI=
  file: build/libs/xlr-jira-extensions-plugin-1.1.0.jar
notifications:
  hipchat:
    rooms:
      secure: iV4Blo4W/Fsq5+x6+xii7+zdLTj2MX7inZlMbfNn6i6SnbEvDTQwJT5NUzkFPqGmpv70PGMssj3qSnHe0IGf5nSeqjcyt2VYDPRLV0YkULM0tXsLQGd6tXOUqOSHCFUkO48zQCWSyYsKXZr6FCxf4pKjTv69oorsQm4auJVKP/E=
